PREFIX owl:  <http://www.w3.org/2002/07/owl#>
PREFIX dct: <http://purl.org/dc/terms/>

SELECT DISTINCT ?vocab {
  # Check only the LOV metadata graph
  GRAPH <http://lov.okfn.org/dataset/lov> {
    {?vocab dct:creator ?agent}
    UNION{?vocab dct:contributor ?agent}
    UNION{?vocab dct:publisher ?agent}
  }
}