PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX voaf: <http://purl.org/vocommons/voaf#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX vann: <http://purl.org/vocab/vann/>

# List agents in LOV. Requires that the agent (Person or Organisation) has a foaf:name
SELECT DISTINCT ?name {
    ?agent foaf:name ?name.
}
# Must have only one so shouldn't have any effect
LIMIT 1