PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX voaf: <http://purl.org/vocommons/voaf#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dct:  <http://purl.org/dc/terms/>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX lexvo: <http://lexvo.org/ontology#>
PREFIX lvont: <http://lexvo.org/ontology#>

# List languages.
SELECT DISTINCT ?iso639P3PCode ?iso639P1Code ?label{
	?lang rdfs:label ?label.
    ?lang lvont:iso639P3Code ?iso639P3PCode.
    ?lang lvont:iso639P1Code ?iso639P1Code.
}