PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX voaf: <http://purl.org/vocommons/voaf#>
PREFIX vann: <http://purl.org/vocab/vann/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT DISTINCT ?element{
	 ?element voaf:occurrencesInDatasets ?occurrencesInDatasets.
	 ?element voaf:reusedByDatasets ?reusedByDatasets.
	 # keep only those with at least 1 occurrence in 1 dataset
	 FILTER((?reusedByDatasets + ?occurrencesInDatasets) >0)
}
