PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
ASK {
  ?class2 rdfs:subClassOf ?class1 .
  ?class1 rdfs:subClassOf ?class0 .
  
  FILTER (isURI(?class2))
  FILTER (STRSTARTS(STR(?class2), STR(?ns)))
  FILTER (isURI(?class0))
  FILTER (STRSTARTS(STR(?class0), STR(?ns)))  
}
