PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
ASK {
  ?class8 rdfs:subClassOf ?class7 .
  ?class7 rdfs:subClassOf ?class6 .
  ?class6 rdfs:subClassOf ?class5 .
  ?class5 rdfs:subClassOf ?class4 .
  ?class4 rdfs:subClassOf ?class3 .
  ?class3 rdfs:subClassOf ?class2 .
  ?class2 rdfs:subClassOf ?class1 .
  ?class1 rdfs:subClassOf ?class0 .
  
  FILTER (isURI(?class8))
  FILTER (STRSTARTS(STR(?class8), STR(?ns)))
  FILTER (isURI(?class0))
  FILTER (STRSTARTS(STR(?class0), STR(?ns)))  
}
